#!/usr/bin/env python
import sys
import os

planner_path = os.path.dirname(os.path.abspath(__file__))
planner = planner_path+"/bfws"
domain = sys.argv[1]
problem = sys.argv[2]
plan = sys.argv[3]

# Incomplete
cmd1 = "{} --domain {}  --problem {} --output {} --1-BFWS 1".format(planner,domain,problem,plan)

# Complete
cmd2 = "{} --domain {}  --problem {} --output {} --BFWS-f5 1 --max_novelty 1".format(planner,domain,problem,plan)


if os.path.exists(plan):
    os.remove(plan)

print("Solving...")
for cmd in [cmd1, cmd2]:

    # Remove empty plan files that may be generated by a failed search
    if os.path.exists(plan):
        with open(plan, 'r') as f:
            contents = f.read()
        if '' == contents.strip():
            os.remove(plan)
    
    # Only run the next command if we don't have a solution
    if not os.path.exists(plan):
        print(cmd)
        os.system(cmd)

print("Done!")